# fly.toml app configuration file generated for setlist-console on 2024-08-25T01:22:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'setlist-console'
primary_region = 'iad'

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  REDIS_PORT="6379"
  REDIS_URL="fly-setlist-console.upstash.io"